version: '3.8'
services:
  #databases
  mysql-warehouse:
    image: mysql:8
    restart: always
    container_name: mysql-warehouse
    ports:
      - "3307:3306" # Expose container's port 3306 locally on port 3307
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_ROOT_USER: root_mysql
      - MYSQL_DATABASE_NAME: warehouse
    volumes:
      - mysql-db-user-data: /var/lib/mysql
    networks:
      - backend-network

  mongodb-clients:
    image: mongo:5
    restart: always
    container_name: mongodb-clients
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: clients
      # Replica Set configuration (for production/HA setups)
      # MONGOD_REPLICA_SET_NAME: rs0
    volumes:
      - mongo-db-client-data: /data/db
    networks:
      - backend-network

  #modules
  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    container_name: warehouse-service
    ports:
      -"3002:3002"
    environment:
      NODE_ENV: development
      DATABASE_HOST: mysql-warehouse
      DATABASE_PORT: 3307
    env_file:
      - ./warehouse-service/.env_file
    depends_on:
      - mysql-warehouse
    
  clients-service:
    build: ./clients-service
    container_name: clients-service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
    env_file:
      - ./clients-service/.env_file
    depends_on:
      - mongodb-clients
    networks:
      - backend-network
    
  sales-service:
    build: ./sales-service
    container_name: sales-service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    env_file:
      - ./sales-service/.env_file
    depends_on:
      - mongodb-clients
      - mysql-warehouse
    networks:
      - backend-network

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVICE_WAREHOUSE_URL: http://warehouse:3002
      - SERVICE_SALES_URL: http://sales:3001
      - SERVICE_CLIENTS_URL: http://warehouse:3003
    depends_on:
      - warehouse-service
      - clients-service
      - sales-service
      

